// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfOVwKIXhK562UMCbEg72c54NUUJ76NLM',
    appId: '1:28971366771:web:8c2ef3b3ebf64ba88cad06',
    messagingSenderId: '28971366771',
    projectId: 'ecommerceapp-1b38f',
    authDomain: 'ecommerceapp-1b38f.firebaseapp.com',
    storageBucket: 'ecommerceapp-1b38f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGAjHfGQZna8iPpDmQqt1XZN3t-jnhks',
    appId: '1:28971366771:android:0196586adb3c3ebe8cad06',
    messagingSenderId: '28971366771',
    projectId: 'ecommerceapp-1b38f',
    storageBucket: 'ecommerceapp-1b38f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8h5-wJihtljpueK8VhiyDBBZv62H2Pdg',
    appId: '1:28971366771:ios:1d4296ba2dd269d68cad06',
    messagingSenderId: '28971366771',
    projectId: 'ecommerceapp-1b38f',
    storageBucket: 'ecommerceapp-1b38f.appspot.com',
    iosClientId: '28971366771-5koe312kraa39fn4g1515oi6iqdt62k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
